[tool.black]
exclude = '''
/(
  \.git
  | \.mypy_cache
  | \.tox
  | \.pytest_cache
  | venv/
  | virtualenv/
  | versions/
)/
'''
line-length = 88

[tool.isort]
atomic = true
honor_noqa = true
line_length = 88
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["git", "__pycache__", "venv", "virtualenv", ".tox", ".pytest_cache"]
src_paths = ["isort", "test"]
